apiVersion: v1
kind: ServiceAccount
metadata:
  name: chn-001-dsh-bff
  # IRSA annotation is patched by overlay/dev/ once Terraform creates the
  # corresponding IAM role per BNK.TECH.CAP.IDENTITY.001.WORKLOAD.
  annotations:
    reliever.io/derived-from: BNK.TECH.CAP.IDENTITY.001.WORKLOAD
