apiVersion: v1
kind: ServiceAccount
metadata:
  name: sup-002-ben-backend
  annotations:
    # IRSA annotation is patched by overlay/dev/ once Terraform creates
    # the corresponding IAM role per BNK.TECH.CAP.IDENTITY.001.WORKLOAD.
    reliever.io/derived-from: BNK.TECH.CAP.IDENTITY.001.WORKLOAD
automountServiceAccountToken: true
