apiVersion: v1
kind: Service
metadata:
  name: bsp-001-tie-stub
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bsp-001-tie-stub
  ports:
    - name: http
      port: 20393
      targetPort: http
      protocol: TCP
