#!/usr/bin/env python3
"""
sketch_miro.py — Render the Reliever process layer as an Event-Storming-style
Miro board.

The DDD process model (aggregates, commands, policies, read-models, bus
topology) is authored by the `/process` skill in the **reliever-knowledge**
repo and consumed here **read-only** via `rlv-knowledge process <CAP_ID>` —
exactly like the BCM corpus via `rlv-knowledge pack`. It does not live in this
repo; capabilities are enumerated with `rlv-knowledge process --list` and each
model is fetched with `rlv-knowledge process <CAP> --compact`.

Idempotent: re-runs reconcile the board against the state file
(.banking-miro.state.json, kept next to this script) and emit the minimal
CREATE/UPDATE/DELETE sequence. The Miro REST API v2 is the only supported
runtime path — see .claude/skills/sketch-miro/SKILL.md for the rationale.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import requests

# Source-context prefix on bcm asset IDs (CLI v2.0.0+ namespacing): a two-token
# <ENTERPRISE>.<SCOPE>. head (e.g. BNK.RLVR. / BNK.TECH.) that precedes a known
# asset-type token. The lookahead keeps process-authored tactical IDs
# (AGG.BSP.… / CMD.BSP.… / POL.… / PRJ.… / QRY.…) untouched — only
# CAP/RVT/EVT/OBJ/SUB/RES/CON carry the prefix.
_SRC_CTX_RE = re.compile(
    r"^[A-Z]{2,}\.[A-Z]{2,}\.(?=(?:CAP|RVT|EVT|OBJ|SUB|RES|CON)\.)"
)
# A capability folder name is one that ends with the CAP.<…> token, whether or
# not it carries a source-context prefix (CAP.BSP.001.SCO | BNK.RLVR.CAP.BSP.001.SCO).
_CAP_DIR_RE = re.compile(r"(?:^|\.)CAP\.[A-Z0-9.]+$")
# Capture a full (optionally prefixed) resource-event ID anywhere in a string.
_RVT_ID_RE = re.compile(r"((?:[A-Z]{2,}\.[A-Z]{2,}\.)?RVT\.[A-Z0-9._-]+)")


def _split_src_ctx(asset_id: str) -> tuple[str, str]:
    """Split a bcm asset id into (source-context-prefix, core).

    'BNK.RLVR.RVT.BSP.001.X' -> ('BNK.RLVR.', 'RVT.BSP.001.X')
    'EVT.REF.001.X'          -> ('', 'EVT.REF.001.X')
    'AGG.BSP.001.SCO.FOO'    -> ('', 'AGG.BSP.001.SCO.FOO')   # tactical, untouched
    """
    m = _SRC_CTX_RE.match(asset_id)
    return (asset_id[: m.end()], asset_id[m.end():]) if m else ("", asset_id)

# ──────────────────────────────────────────────────────────────────────────
# Constants and paths
# ──────────────────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parents[3]
# Sidecars live next to this script — the process model itself is served by
# `rlv-knowledge process` from the reliever-knowledge repo and is not on disk here.
SCRIPT_DIR = Path(__file__).resolve().parent
STATE_FILE = SCRIPT_DIR / ".banking-miro.state.json"
URL_FILE = SCRIPT_DIR / "banking-miro.url"
BOARD_NAME = "Reliever — Event Storming (process layer)"
BOARD_DESCRIPTION = (
    "Auto-generated by /sketch-miro from the Reliever process model "
    "(consumed via `rlv-knowledge process`) — do not edit by hand; re-run the "
    "skill to refresh."
)

API_BASE = "https://api.miro.com/v2"

# Miro sticky-note colors (named values supported by the v2 API).
# Valid set: gray, light_yellow, yellow, orange, light_green, green,
# dark_green, cyan, light_pink, pink, violet, red, light_blue, blue,
# dark_blue, black. `light_orange` is NOT a valid Miro v2 color name.
COLOR = {
    "event":            "orange",
    "external_event":   "light_yellow",   # faded warm — closest to "light orange"
    "command":          "light_blue",
    "aggregate":        "yellow",
    "policy":           "violet",
    "read_model":       "light_green",
    "actor":            "light_pink",
}

# Per-capability frame background palette. Pastel hex values picked so
# bright sticky colors (orange/yellow/blue/violet/green/red) remain
# legible against the frame. The actual color of a given capability is
# chosen deterministically by hashing its cap_id, so the same capability
# always gets the same color across runs and across branches.
FRAME_COLORS = [
    "#dbe7f9",  # light blue
    "#dff5d8",  # light green
    "#fff5d3",  # light yellow
    "#f9d8e8",  # light pink
    "#e7d8f9",  # light lavender
    "#d8f9f5",  # light aqua
    "#fde8d3",  # light peach
    "#f0d8d8",  # light rose
    "#d8e8e0",  # light sage
    "#e0e8f0",  # light sky
    "#f5e0d8",  # light sand
    "#ddd8f0",  # light periwinkle
]

# Layout (px). One frame per capability; frames laid out in a 2-column grid.
FRAME_W = 3000
FRAME_H = 2400
FRAME_GAP_X = 400
FRAME_GAP_Y = 400
LANE_TOP = 240            # below the title
LANE_HEIGHT = 360
LANE_PAD_X = 80
STICKY_W = 220
STICKY_H = 160
STICKY_GAP = 32
AGG_W = 360
AGG_H = 240

# Lane vertical positions inside a frame.
LANES = [
    ("events",      LANE_TOP + 0 * LANE_HEIGHT),
    ("commands",    LANE_TOP + 1 * LANE_HEIGHT),
    ("aggregates",  LANE_TOP + 2 * LANE_HEIGHT),
    ("policies",    LANE_TOP + 3 * LANE_HEIGHT),
    ("read_models", LANE_TOP + 4 * LANE_HEIGHT),
]
LANE_LABEL_X = 40

# ──────────────────────────────────────────────────────────────────────────
# Data model
# ──────────────────────────────────────────────────────────────────────────

@dataclass
class Widget:
    """A target widget — a row in the desired-state set."""
    artifact_id: str          # stable, unique per process artifact
    kind: str                 # event | command | aggregate | policy | read_model | external_event | frame | connector | label
    label: str
    x: float = 0.0
    y: float = 0.0
    w: float = STICKY_W
    h: float = STICKY_H
    parent_artifact_id: str | None = None
    # Board-level tags to attach to this sticky. Each entry is a tag TITLE
    # (e.g. "RVT.BSP.004.PAYMENT_GRANTED" or "CAP.BSP.004.AUT"); the
    # reconciler resolves titles to ids, creating the tag on the board if
    # it does not already exist.
    tags: list[str] = field(default_factory=list)
    extra: dict[str, Any] = field(default_factory=dict)


@dataclass
class Connector:
    artifact_id: str          # stable id
    from_artifact_id: str
    to_artifact_id: str
    style: str = "solid"      # solid | dashed
    label: str = ""


# ──────────────────────────────────────────────────────────────────────────
# State file
# ──────────────────────────────────────────────────────────────────────────

def load_state() -> dict[str, Any]:
    state: dict[str, Any]
    if STATE_FILE.exists():
        try:
            state = json.loads(STATE_FILE.read_text())
        except json.JSONDecodeError:
            print(f"[warn] {STATE_FILE} is corrupt — starting from scratch", file=sys.stderr)
            state = {}
    else:
        state = {}
    # Ensure all expected keys exist for backwards compatibility with
    # state files written by older versions of the script.
    state.setdefault("board_id", None)
    state.setdefault("widgets", {})
    state.setdefault("tags", {})         # {tag_title: tag_id}
    state.setdefault("widget_tags", {})  # {widget_artifact_id: [tag_title, ...]}
    return state


def save_state(state: dict[str, Any]) -> None:
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2, sort_keys=True))


def save_url(url: str) -> None:
    URL_FILE.write_text(url + "\n")


# ──────────────────────────────────────────────────────────────────────────
# Miro REST API client (just the parts we need)
# ──────────────────────────────────────────────────────────────────────────

class MiroClient:
    def __init__(self, token: str, dry_run: bool = False) -> None:
        self.session = requests.Session()
        self.session.headers.update({
            "Authorization": f"Bearer {token}",
            "Accept": "application/json",
            "Content-Type": "application/json",
        })
        self.dry_run = dry_run
        self.api_calls = 0
        self.retries = 0

    def _request(self, method: str, path: str, *, body: dict | None = None) -> dict:
        if self.dry_run and method in {"POST", "PATCH", "DELETE"}:
            return {"id": f"dryrun-{self.api_calls}"}
        url = f"{API_BASE}{path}"
        for attempt in range(5):
            self.api_calls += 1
            resp = self.session.request(method, url, json=body)
            if resp.status_code == 429:
                self.retries += 1
                wait = float(resp.headers.get("Retry-After", "2")) + 0.5 * attempt
                time.sleep(wait)
                continue
            if resp.status_code >= 400:
                raise RuntimeError(
                    f"Miro {method} {path} → {resp.status_code}: {resp.text[:500]}"
                )
            if resp.status_code == 204:
                return {}
            return resp.json()
        raise RuntimeError(f"Miro {method} {path} — exhausted retries on 429")

    # ── Boards ──
    def create_board(self) -> dict:
        return self._request("POST", "/boards", body={
            "name": BOARD_NAME,
            "description": BOARD_DESCRIPTION,
            "policy": {"sharingPolicy": {"access": "private"}},
        })

    def get_board(self, board_id: str) -> dict:
        return self._request("GET", f"/boards/{board_id}")

    def delete_board_widget(self, board_id: str, item_id: str) -> None:
        self._request("DELETE", f"/boards/{board_id}/items/{item_id}")

    # ── Frames ──
    def create_frame(self, board_id: str, *, title: str, x: float, y: float,
                     w: float, h: float, fill_color: str | None = None) -> dict:
        body: dict[str, Any] = {
            "data": {"title": title, "format": "custom", "type": "freeform"},
            "position": {"x": x, "y": y},
            "geometry": {"width": w, "height": h},
        }
        if fill_color:
            body["style"] = {"fillColor": fill_color}
        return self._request("POST", f"/boards/{board_id}/frames", body=body)

    def update_frame(self, board_id: str, item_id: str, *, title: str,
                     fill_color: str | None = None) -> dict:
        body: dict[str, Any] = {"data": {"title": title}}
        if fill_color:
            body["style"] = {"fillColor": fill_color}
        return self._request("PATCH", f"/boards/{board_id}/frames/{item_id}", body=body)

    # ── Sticky notes ──
    def create_sticky(self, board_id: str, *, content: str, color: str, x: float, y: float,
                      w: float, parent_id: str | None) -> dict:
        body: dict[str, Any] = {
            "data": {"content": content, "shape": "square"},
            "style": {"fillColor": color},
            "position": {"x": x, "y": y},
            "geometry": {"width": w},
        }
        if parent_id:
            body["parent"] = {"id": parent_id}
        return self._request("POST", f"/boards/{board_id}/sticky_notes", body=body)

    def update_sticky(self, board_id: str, item_id: str, *, content: str, color: str) -> dict:
        return self._request("PATCH", f"/boards/{board_id}/sticky_notes/{item_id}", body={
            "data": {"content": content, "shape": "square"},
            "style": {"fillColor": color},
        })

    # ── Connectors ──
    def create_connector(self, board_id: str, *, start_id: str, end_id: str,
                         style: str, label: str) -> dict:
        stroke_style = "dashed" if style == "dashed" else "normal"
        body: dict[str, Any] = {
            "startItem": {"id": start_id},
            "endItem":   {"id": end_id},
            "style": {
                "strokeColor": "#1a1a1a",
                "strokeStyle": stroke_style,
                "strokeWidth": "2",
                "endStrokeCap": "arrow",
                "startStrokeCap": "none",
            },
        }
        if label:
            body["captions"] = [{"content": label}]
        return self._request("POST", f"/boards/{board_id}/connectors", body=body)

    def delete_connector(self, board_id: str, item_id: str) -> None:
        self._request("DELETE", f"/boards/{board_id}/connectors/{item_id}")

    # ── Tags (board-level entities that can be attached to items) ──
    def list_tags(self, board_id: str) -> list[dict]:
        """List all tags defined on the board.

        The v2 tags endpoint paginates with `limit` + `offset` (it returns
        `total`, `size`, `offset`, `limit`; no cursor). We loop until we
        have collected `total` items.
        """
        out: list[dict] = []
        offset = 0
        page_size = 50
        while True:
            res = self._request(
                "GET",
                f"/boards/{board_id}/tags?limit={page_size}&offset={offset}",
            )
            chunk = res.get("data", []) or []
            out.extend(chunk)
            total = int(res.get("total", len(out)) or len(out))
            offset += len(chunk)
            if not chunk or offset >= total:
                return out

    def create_tag(self, board_id: str, *, title: str, fill_color: str = "gray") -> dict:
        return self._request("POST", f"/boards/{board_id}/tags", body={
            "title": title,
            "fillColor": fill_color,
        })

    def attach_tag(self, board_id: str, item_id: str, tag_id: str) -> None:
        # Miro v2 attach uses a query parameter, no body.
        self._request("POST", f"/boards/{board_id}/items/{item_id}?tag_id={tag_id}")

    def detach_tag(self, board_id: str, item_id: str, tag_id: str) -> None:
        self._request("DELETE", f"/boards/{board_id}/items/{item_id}?tag_id={tag_id}")


# ──────────────────────────────────────────────────────────────────────────
# Process model loader
# ──────────────────────────────────────────────────────────────────────────

@dataclass
class Capability:
    cap_id: str
    aggregates: list[dict]
    commands: list[dict]
    policies: list[dict]
    read_models: list[dict]   # both PRJ.* and QRY.* flattened
    bus: dict
    name: str = ""

    @property
    def short_id(self) -> str:
        return self.cap_id


def _run_bcm_pack_process(*args: str) -> tuple[int, str, str]:
    """Invoke `rlv-knowledge process <args>` and return (returncode, stdout, stderr).

    The leading '# knowledge-base …' provenance line and any '[rlv-knowledge] …'
    log lines are emitted on stderr by the CLI, so stdout is the clean
    payload (a cap-id list for `--list`, JSON for `<CAP> --compact`)."""
    try:
        proc = subprocess.run(
            ["rlv-knowledge", "process", *args],
            capture_output=True, text=True, check=False,
        )
    except FileNotFoundError as exc:
        raise RuntimeError(
            "rlv-knowledge is not installed / not on PATH — cannot fetch the "
            "process model (it lives in the reliever-knowledge repo, served "
            "via `rlv-knowledge process`)."
        ) from exc
    return proc.returncode, proc.stdout, proc.stderr


def list_process_capabilities() -> list[str]:
    """Enumerate every capability that has a process model, via
    `rlv-knowledge process --list`. One cap id per stdout line."""
    rc, out, err = _run_bcm_pack_process("--list")
    if rc != 0:
        raise RuntimeError(f"`rlv-knowledge process --list` failed (exit {rc}): {err.strip()}")
    return [ln.strip() for ln in out.splitlines() if ln.strip() and not ln.startswith("#")]


def _model_doc(env: dict, stem: str) -> dict:
    """Return the parsed mapping of one model file from a `rlv-knowledge process`
    envelope. When `.parsed` is null (commands.yaml / read-models.yaml often
    fail strict YAML on `api_binding: { path: /x/{id} }` flow mappings),
    DEGRADE GRACEFULLY to an empty dict — we deliberately do NOT re-parse
    `.raw` with pyyaml, which fails identically."""
    entry = (env.get("model") or {}).get(stem) or {}
    parsed = entry.get("parsed")
    return parsed if isinstance(parsed, dict) else {}


def load_capability(cap_id: str) -> Capability:
    """Fetch and assemble one capability's process model from
    `rlv-knowledge process <cap_id> --compact`."""
    rc, out, err = _run_bcm_pack_process(cap_id, "--compact")
    if rc != 0:
        raise RuntimeError(
            f"`rlv-knowledge process {cap_id}` failed (exit {rc}): {err.strip()}"
        )
    env = json.loads(out)
    agg = _model_doc(env, "aggregates").get("aggregates", []) or []
    cmd = _model_doc(env, "commands").get("commands", []) or []
    pol = _model_doc(env, "policies").get("policies", []) or []
    rm_doc = _model_doc(env, "read-models")
    rms: list[dict] = []
    for p in (rm_doc.get("read_models", []) or []):
        rms.append({"_kind": "projection", **p})
    for q in (rm_doc.get("queries", []) or []):
        rms.append({"_kind": "query", **q})
    bus = _model_doc(env, "bus")
    name = ((env.get("meta") or {}).get("capability") or "") or ""
    return Capability(
        cap_id=cap_id, aggregates=agg, commands=cmd, policies=pol,
        read_models=rms, bus=bus, name=name,
    )


def discover_capabilities(only: str | None = None) -> list[Capability]:
    cap_ids = list_process_capabilities()
    # Only render source-context-prefixed capability ids (e.g.
    # BNK.RLVR.CAP.…), skipping any stale pre-namespacing short forms
    # (CAP.BSP.004.ENV) the CLI may still surface.
    cap_ids = [
        c for c in cap_ids if _CAP_DIR_RE.search(c) and _SRC_CTX_RE.match(c)
    ]
    if only:
        cap_ids = [c for c in cap_ids if c == only]
        if not cap_ids:
            raise RuntimeError(f"No process model matching {only} (via `rlv-knowledge process`)")
    return [load_capability(c) for c in sorted(cap_ids)]


# ──────────────────────────────────────────────────────────────────────────
# Layout planner
# ──────────────────────────────────────────────────────────────────────────

def _frame_origin(index: int) -> tuple[float, float]:
    col = index % 2
    row = index // 2
    x = col * (FRAME_W + FRAME_GAP_X)
    y = row * (FRAME_H + FRAME_GAP_Y)
    return x, y


def _truncate(s: str, n: int = 90) -> str:
    s = (s or "").strip().replace("\n", " ")
    return s if len(s) <= n else s[: n - 1] + "…"


def _short(name: str) -> str:
    """Strip the AGG/CMD/POL/PRJ/QRY prefix and capability path for compact stickies."""
    parts = name.split(".")
    if len(parts) >= 5:
        return parts[-1]
    return name


def _frame_color(cap_id: str) -> str:
    """Pick a deterministic pastel hex color for a capability frame."""
    import hashlib
    digest = hashlib.md5(cap_id.encode("utf-8")).digest()
    idx = int.from_bytes(digest[:4], "big") % len(FRAME_COLORS)
    return FRAME_COLORS[idx]


def _humanize(name: str) -> str:
    """Turn an artifact id into a clean sticky label.

    Examples:
        RVT.BSP.004.PAYMENT_GRANTED              -> 'PAYMENT GRANTED'
        AGG.BSP.001.SCO.SCORE_OF_BENEFICIARY     -> 'SCORE OF BENEFICIARY'
        CMD.BSP.001.SCO.COMPUTE_ENTRY_SCORE      -> 'COMPUTE ENTRY SCORE'
    """
    last = name.split(".")[-1] if "." in name else name
    return last.replace("_", " ").strip()


# Map an id-style tag title (CAP., AGG., CMD., POL., RVT., PRJ., QRY.) to a
# valid Miro tag fill color. Miro's tag palette is: red, magenta, violet,
# light_green, green, dark_green, cyan, blue, dark_blue, yellow, gray, black.
def _tag_fill_color(title: str) -> str:
    if title == "external":
        return "magenta"   # meta-flag: source not yet authored in /process
    if title == "business event":
        return "yellow"    # type-flag: EXT_EVT sticky — pending RVT/subscription
    # Strip the optional source-context prefix (BNK.RLVR. / BNK.TECH.) so
    # bcm asset IDs classify by their type token regardless of namespacing.
    _, core = _split_src_ctx(title)
    if core.startswith("CAP."):
        return "cyan"
    if core.startswith("AGG."):
        return "yellow"
    if core.startswith("CMD."):
        return "blue"
    if core.startswith("POL."):
        return "violet"
    if core.startswith("RVT."):
        return "red"
    if core.startswith("EVT."):
        return "magenta"   # business event — distinct from RVT (resource)
    if core.startswith("PRJ.") or core.startswith("QRY."):
        return "green"
    return "gray"


def plan_widgets(caps: list[Capability]) -> tuple[list[Widget], list[Connector]]:
    widgets: list[Widget] = []
    connectors: list[Connector] = []

    # First pass — frames.
    for i, cap in enumerate(caps):
        ox, oy = _frame_origin(i)
        cx = ox + FRAME_W / 2
        cy = oy + FRAME_H / 2
        widgets.append(Widget(
            artifact_id=f"FRAME:{cap.cap_id}",
            kind="frame",
            label=cap.cap_id,
            x=cx, y=cy, w=FRAME_W, h=FRAME_H,
            extra={"fill_color": _frame_color(cap.cap_id)},
        ))

    # Cross-frame index: which capability emits each RVT? Built once, used
    # below to decide whether a subscription should reference the source
    # cap's emitted-event sticky directly (cross-frame arrow) or whether
    # the source is truly external (no local emitter found → keep an
    # external sticky in the consumer frame).
    rvt_owner: dict[str, str] = {}
    for cap in caps:
        for agg in cap.aggregates:
            for rvt in (agg.get("emitted_resource_events", []) or []):
                rvt_owner.setdefault(rvt, cap.cap_id)

    # Second pass — stickies inside each frame.
    for i, cap in enumerate(caps):
        frame_aid = f"FRAME:{cap.cap_id}"

        # Miro v2 places child items with `relativeTo: parent_top_left`.
        # Origin (0,0) is the parent frame's top-left corner; (FRAME_W, FRAME_H) is bottom-right.
        # The item position itself uses `origin: center`, so we offset by half-size.
        def rel_pos(lane_y: float, slot: int) -> tuple[float, float]:
            x = LANE_PAD_X + STICKY_W / 2 + slot * (STICKY_W + STICKY_GAP)
            y = lane_y
            return x, y

        # Lane Y lookups
        lane_y = dict(LANES)

        # ── Aggregates ──
        for slot, agg in enumerate(cap.aggregates):
            aid = agg["id"]
            ax, ay = rel_pos(lane_y["aggregates"], slot)
            widgets.append(Widget(
                artifact_id=f"AGG:{aid}",
                kind="aggregate",
                label=_humanize(aid),
                x=ax, y=ay, w=AGG_W, h=AGG_H,
                parent_artifact_id=frame_aid,
                tags=[aid, cap.cap_id],
            ))

        # ── Commands ──
        for slot, cmd in enumerate(cap.commands):
            cid = cmd["id"]
            cx_, cy_ = rel_pos(lane_y["commands"], slot)
            widgets.append(Widget(
                artifact_id=f"CMD:{cid}",
                kind="command",
                label=_humanize(cid),
                x=cx_, y=cy_,
                parent_artifact_id=frame_aid,
                tags=[cid, cap.cap_id],
            ))
            # CMD → AGG (accepted_by)
            target_agg = cmd.get("accepted_by")
            if target_agg:
                connectors.append(Connector(
                    artifact_id=f"CONN:{cid}->AGG",
                    from_artifact_id=f"CMD:{cid}",
                    to_artifact_id=f"AGG:{target_agg}",
                    style="solid",
                ))

        # ── Events emitted (orange) ──
        # Collect emitted RVTs by walking aggregates' emitted_resource_events.
        slot = 0
        emitted_seen: set[str] = set()
        for agg in cap.aggregates:
            for rvt in (agg.get("emitted_resource_events", []) or []):
                if rvt in emitted_seen:
                    continue
                emitted_seen.add(rvt)
                ex, ey = rel_pos(lane_y["events"], slot)
                widgets.append(Widget(
                    artifact_id=f"RVT:{cap.cap_id}:{rvt}",
                    kind="event",
                    label=_humanize(rvt),
                    x=ex, y=ey,
                    parent_artifact_id=frame_aid,
                    tags=[rvt, cap.cap_id],
                ))
                # AGG → RVT (emits)
                connectors.append(Connector(
                    artifact_id=f"CONN:{agg['id']}->{rvt}",
                    from_artifact_id=f"AGG:{agg['id']}",
                    to_artifact_id=f"RVT:{cap.cap_id}:{rvt}",
                    style="solid",
                ))
                slot += 1

        # ── External (consumed) events — same lane, after local emitted ones ──
        # Two sources of consumed-event signals are merged here:
        #   1. `bus.yaml.subscriptions`            → resource events (RVT.*)
        #   2. `policies[*].listens_to[*]`         → resource OR business
        #                                            events (RVT.* or EVT.*)
        # The script only places a sticky when the source is OUT of the
        # modelled capability set (rvt_owner has no entry; the set comes from
        # `rlv-knowledge process --list`). When the
        # source is one of the local capabilities, the policy connector
        # reaches across frames to the emitter's sticky — no duplicate.
        # `business_event` (EVT.*) is the canonical fallback when the
        # upstream capability has not been process-modelled yet and its
        # paired RVT is therefore unknown.
        consumed_rvts: list[tuple[str, str]] = []  # (rvt, source_cap)
        seen_consumed: set[str] = set()
        for sub in (cap.bus.get("subscriptions", []) or []):
            bp = sub.get("binding_pattern", "")
            # Extract the full (optionally source-context-prefixed) RVT id so
            # it matches the emitted-side keys in `rvt_owner` verbatim.
            m_rvt = _RVT_ID_RE.search(bp)
            rvt_part = m_rvt.group(1) if m_rvt else bp
            if rvt_part and rvt_part not in seen_consumed:
                seen_consumed.add(rvt_part)
                consumed_rvts.append((rvt_part, sub.get("source_capability", "?")))

        consumed_evts: list[tuple[str, str]] = []  # (evt, source_cap)
        seen_evts: set[str] = set()
        for pol in cap.policies:
            for entry in (pol.get("listens_to") or []):
                evt = entry.get("business_event")
                if not evt or evt in seen_evts or evt in {"TBD", "?", ""}:
                    continue
                seen_evts.add(evt)
                # Infer L2 source cap from the EVT id, preserving any
                # source-context prefix:
                #   BNK.RLVR.EVT.REF.001.TIER_DEFINITION_UPDATED
                #     → BNK.RLVR.CAP.REF.001
                pfx, core = _split_src_ctx(evt)
                parts = core.split(".")
                src_cap = f"{pfx}CAP.{parts[1]}.{parts[2]}" if len(parts) >= 4 else "?"
                consumed_evts.append((evt, src_cap))

        for (rvt, src_cap) in consumed_rvts:
            if rvt in rvt_owner:
                continue
            ex, ey = rel_pos(lane_y["events"], slot)
            widgets.append(Widget(
                artifact_id=f"EXT_RVT:{cap.cap_id}:{rvt}",
                kind="external_event",
                label=_humanize(rvt),
                x=ex, y=ey,
                parent_artifact_id=frame_aid,
                # Third tag flags the sticky as external/unauthored — the
                # upstream capability isn't part of the modelled `/process`
                # set yet. Removed automatically once it gets authored and
                # the rvt is found in `rvt_owner` (sticky stops being made).
                tags=[rvt, src_cap, "external"],
            ))
            slot += 1

        for (evt, src_cap) in consumed_evts:
            ex, ey = rel_pos(lane_y["events"], slot)
            widgets.append(Widget(
                artifact_id=f"EXT_EVT:{cap.cap_id}:{evt}",
                kind="external_event",
                label=_humanize(evt),
                x=ex, y=ey,
                parent_artifact_id=frame_aid,
                # 4 tags on every EXT_EVT sticky:
                #   - full EVT id (magenta) — the canonical business event identity
                #   - source CAP id (cyan)  — the inferred upstream capability
                #   - "external"  (magenta) — meta-flag: source not yet authored
                #   - "business event" (yellow) — type-flag: pending RVT/subscription;
                #                                explicit reminder that BCM work is
                #                                still owed before this can be
                #                                promoted to a resource_event.
                tags=[evt, src_cap, "external", "business event"],
            ))
            slot += 1

        # ── Policies (violet) ──
        for slot_p, pol in enumerate(cap.policies):
            pid = pol["id"]
            px, py = rel_pos(lane_y["policies"], slot_p)
            widgets.append(Widget(
                artifact_id=f"POL:{pid}",
                kind="policy",
                label=_humanize(pid),
                x=px, y=py,
                parent_artifact_id=frame_aid,
                tags=[pid, cap.cap_id],
            ))
            # POL → CMD (issues)
            issued = pol.get("issues")
            if issued:
                connectors.append(Connector(
                    artifact_id=f"CONN:{pid}->{issued}",
                    from_artifact_id=f"POL:{pid}",
                    to_artifact_id=f"CMD:{issued}",
                    style="dashed",
                ))
            # event → POL (subscription).  Resolution order:
            #   1. `resource_event` (RVT.*) emitted by a LOCAL capability
            #      → cross-frame connector to that emitter's RVT sticky.
            #   2. `resource_event` not in rvt_owner
            #      → arrow from the consumer's own EXT_RVT sticky.
            #   3. `business_event` (EVT.*) — the upstream cap has not
            #      been process-modelled yet, so we use the EXT_EVT
            #      sticky placed earlier from this scan.
            #   4. Placeholder values (TBD / ? / empty) → silently skipped.
            for entry in (pol.get("listens_to", []) or []):
                rvt = entry.get("resource_event")
                evt = entry.get("business_event")
                if rvt and rvt not in {"TBD", "?", ""}:
                    if rvt in rvt_owner:
                        src_aid = f"RVT:{rvt_owner[rvt]}:{rvt}"
                    else:
                        src_aid = f"EXT_RVT:{cap.cap_id}:{rvt}"
                elif evt and evt not in {"TBD", "?", ""}:
                    src_aid = f"EXT_EVT:{cap.cap_id}:{evt}"
                else:
                    continue
                connectors.append(Connector(
                    artifact_id=f"CONN:{src_aid}->{pid}",
                    from_artifact_id=src_aid,
                    to_artifact_id=f"POL:{pid}",
                    style="dashed",
                ))

        # ── Read models (PRJ + QRY, green) ──
        for slot_r, rm in enumerate(cap.read_models):
            rid = rm["id"]
            rx, ry = rel_pos(lane_y["read_models"], slot_r)
            widgets.append(Widget(
                artifact_id=f"RM:{rid}",
                kind="read_model",
                label=_humanize(rid),
                x=rx, y=ry,
                parent_artifact_id=frame_aid,
                tags=[rid, cap.cap_id],
            ))

            # RVT → PRJ  (projection.fed_by)
            #   Each RVT in `fed_by` produces an arrow into the projection.
            #   If the RVT is emitted by another local cap, the arrow
            #   reaches across frames (using rvt_owner). If the source is
            #   truly external, the arrow starts at the EXT_RVT sticky in
            #   this cap's events lane.
            if rm.get("_kind") != "query":
                for rvt in (rm.get("fed_by") or []):
                    if rvt in rvt_owner:
                        src_aid = f"RVT:{rvt_owner[rvt]}:{rvt}"
                    else:
                        src_aid = f"EXT_RVT:{cap.cap_id}:{rvt}"
                    connectors.append(Connector(
                        artifact_id=f"CONN:{src_aid}->RM:{rid}",
                        from_artifact_id=src_aid,
                        to_artifact_id=f"RM:{rid}",
                        style="solid",
                    ))

            # PRJ → QRY  (query.served_by)
            #   `served_by` is single-valued in the YAML: the projection
            #   the query runs against. A query may also live in another
            #   capability than its projection — we resolve by full id.
            if rm.get("_kind") == "query":
                served_by = rm.get("served_by")
                if served_by:
                    connectors.append(Connector(
                        artifact_id=f"CONN:RM:{served_by}->RM:{rid}",
                        from_artifact_id=f"RM:{served_by}",
                        to_artifact_id=f"RM:{rid}",
                        style="solid",
                    ))

    return widgets, connectors


# ──────────────────────────────────────────────────────────────────────────
# Reconciler
# ──────────────────────────────────────────────────────────────────────────

def reconcile(
    client: MiroClient, board_id: str, widgets: list[Widget], connectors: list[Connector],
    state: dict[str, Any], scope_cap: str | None,
) -> dict[str, int]:
    counts = {"create": 0, "update": 0, "delete": 0, "tag_attach": 0, "tag_detach": 0}
    widget_ids = state.setdefault("widgets", {})
    tag_ids: dict[str, str] = state.setdefault("tags", {})         # title -> id
    widget_tags: dict[str, list[str]] = state.setdefault("widget_tags", {})

    # Bootstrap the tag cache from the board so we don't recreate tags
    # that were already produced on a previous run, but lost from local
    # state (e.g. user wiped the state file but not the board).
    if not tag_ids:
        for t in client.list_tags(board_id):
            title = t.get("title")
            tid = t.get("id")
            if title and tid:
                tag_ids[title] = tid

    target_aids = {w.artifact_id for w in widgets} | {c.artifact_id for c in connectors}

    # Frames first (children depend on them). Then non-connector widgets. Then connectors.
    frames = [w for w in widgets if w.kind == "frame"]
    items = [w for w in widgets if w.kind != "frame"]

    # ── Frames ──
    for w in frames:
        existing = widget_ids.get(w.artifact_id)
        fill = w.extra.get("fill_color") if w.extra else None
        if existing:
            try:
                client.update_frame(board_id, existing, title=w.label, fill_color=fill)
                counts["update"] += 1
            except RuntimeError as e:
                # Frame may be locked on the board (user pinned it manually).
                # Skip and warn — the rest of the reconcile must continue.
                if "locked" in str(e).lower():
                    print(f"[warn] frame {w.artifact_id} is locked on the board "
                          f"— skipping PATCH (unlock it on Miro to refresh title/color)",
                          file=sys.stderr)
                else:
                    raise
        else:
            res = client.create_frame(board_id, title=w.label, x=w.x, y=w.y,
                                      w=w.w, h=w.h, fill_color=fill)
            widget_ids[w.artifact_id] = res.get("id", f"new-{counts['create']}")
            counts["create"] += 1

    # ── Stickies ──
    for w in items:
        parent_id = widget_ids.get(w.parent_artifact_id) if w.parent_artifact_id else None
        existing = widget_ids.get(w.artifact_id)
        color = COLOR.get(w.kind, "light_gray")
        if existing:
            try:
                client.update_sticky(board_id, existing, content=w.label, color=color)
                counts["update"] += 1
            except RuntimeError as e:
                if "locked" in str(e).lower():
                    print(f"[warn] sticky {w.artifact_id} is locked — skipping PATCH",
                          file=sys.stderr)
                else:
                    raise
        else:
            # Children of a frame use position relative to the frame center; otherwise board-relative.
            res = client.create_sticky(
                board_id, content=w.label, color=color,
                x=w.x, y=w.y, w=w.w, parent_id=parent_id,
            )
            widget_ids[w.artifact_id] = res.get("id", f"new-{counts['create']}")
            counts["create"] += 1

        # ── Tag sync ──
        # Compare the widget's desired tag titles against what we last
        # applied (state.widget_tags[aid]); only attach/detach the delta.
        item_id = widget_ids.get(w.artifact_id)
        if item_id:
            desired = list(dict.fromkeys(w.tags))   # preserve order, drop dupes
            recorded = list(widget_tags.get(w.artifact_id, []))
            desired_set, recorded_set = set(desired), set(recorded)
            if desired_set != recorded_set:
                # Resolve missing tag ids (create on the board if absent).
                for title in desired:
                    if title not in tag_ids:
                        tag = client.create_tag(
                            board_id, title=title, fill_color=_tag_fill_color(title)
                        )
                        tag_ids[title] = tag["id"]
                # Attach the new tags.
                for title in desired_set - recorded_set:
                    try:
                        client.attach_tag(board_id, item_id, tag_ids[title])
                        counts["tag_attach"] += 1
                    except RuntimeError as e:
                        # Already attached → 409/400. Treat as success.
                        if "409" in str(e) or "400" in str(e):
                            pass
                        else:
                            print(f"[warn] attach {title} on {w.artifact_id}: {e}",
                                  file=sys.stderr)
                # Detach the obsolete ones.
                for title in recorded_set - desired_set:
                    tid = tag_ids.get(title)
                    if not tid:
                        continue
                    try:
                        client.detach_tag(board_id, item_id, tid)
                        counts["tag_detach"] += 1
                    except RuntimeError as e:
                        print(f"[warn] detach {title} on {w.artifact_id}: {e}",
                              file=sys.stderr)
                widget_tags[w.artifact_id] = sorted(desired_set)

    # ── Connectors (after stickies; require both endpoints to exist) ──
    for c in connectors:
        existing = widget_ids.get(c.artifact_id)
        start_id = widget_ids.get(c.from_artifact_id)
        end_id = widget_ids.get(c.to_artifact_id)
        if not start_id or not end_id:
            # Endpoint not on the board (e.g. cross-cap subscription whose source frame is not in scope)
            continue
        if existing:
            # Connector PATCH is supported but rarely useful — endpoints don't change in a re-run
            counts["update"] += 1
            continue
        res = client.create_connector(board_id, start_id=start_id, end_id=end_id,
                                      style=c.style, label=c.label)
        widget_ids[c.artifact_id] = res.get("id", f"new-{counts['create']}")
        counts["create"] += 1

    # ── Stale items: in state but no longer in target ──
    # When --cap is used we only delete artifacts BELONGING TO that cap,
    # to avoid wiping the rest of the board.
    def is_in_scope(aid: str) -> bool:
        if not scope_cap:
            return True
        # FRAME:CAP.<id>     CMD:CMD.<id-with-cap>      RVT:CAP.<id>:RVT.…
        return scope_cap in aid

    stale = [aid for aid in widget_ids
             if aid not in target_aids and is_in_scope(aid) and aid != "_meta"]
    for aid in stale:
        wid = widget_ids[aid]
        try:
            # Try as a generic item (Miro's items endpoint accepts any kind)
            client.delete_board_widget(board_id, wid)
        except RuntimeError as e:
            if "locked" in str(e).lower():
                print(f"[warn] {aid} is locked on the board — skipping delete",
                      file=sys.stderr)
            else:
                print(f"[warn] could not delete {aid} ({wid}): {e}", file=sys.stderr)
            continue
        widget_ids.pop(aid, None)
        widget_tags.pop(aid, None)
        counts["delete"] += 1

    return counts


# ──────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(description="Sync the Reliever process model (via `rlv-knowledge process`) to a Miro board.")
    parser.add_argument("--cap", help="Sync only this capability (e.g. BNK.RLVR.CAP.CHN.001.DSH).", default=None)
    parser.add_argument("--dry-run", action="store_true", help="Print the change plan without calling the API.")
    parser.add_argument("--rebuild", action="store_true", help="Wipe known widgets and rebuild from scratch.")
    parser.add_argument("--token", default=os.environ.get("MIRO_ACCESS_TOKEN"),
                        help="Miro access token (defaults to MIRO_ACCESS_TOKEN env var).")
    args = parser.parse_args()

    if not args.token and not args.dry_run:
        print("ERROR: MIRO_ACCESS_TOKEN env var is not set. See .claude/skills/sketch-miro/SKILL.md Step 0.",
              file=sys.stderr)
        return 1

    try:
        caps = discover_capabilities(only=args.cap)
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2
    if not caps:
        print("No process-modelled capabilities discovered via `rlv-knowledge process --list`.", file=sys.stderr)
        return 2

    print(f"Discovered {len(caps)} capabilities:")
    for c in caps:
        print(f"  • {c.cap_id}  ({len(c.aggregates)} agg / {len(c.commands)} cmd / "
              f"{len(c.policies)} pol / {len(c.read_models)} read-model)")

    widgets, connectors = plan_widgets(caps)
    print(f"\nPlanned {len(widgets)} widgets and {len(connectors)} connectors.")

    if args.dry_run:
        # Show a tiny sample so the user can sanity-check the layout.
        from collections import Counter
        by_kind = Counter(w.kind for w in widgets)
        print("\nDry-run breakdown:")
        for k, n in sorted(by_kind.items()):
            print(f"  {k:>16}: {n}")
        print(f"\n  connectors: {len(connectors)}")
        print("\nNo API calls made. Re-run without --dry-run to apply.")
        return 0

    state = load_state()
    client = MiroClient(args.token)

    if args.rebuild and state.get("widgets"):
        print("\n--rebuild: deleting known widgets…")
        for aid, wid in list(state["widgets"].items()):
            try:
                client.delete_board_widget(state["board_id"], wid)
            except RuntimeError as e:
                print(f"[warn] could not delete {aid}: {e}", file=sys.stderr)
            state["widgets"].pop(aid, None)
        save_state(state)

    # Resolve / create board.
    board_id = state.get("board_id")
    if not board_id:
        print("\nNo existing board recorded — creating a new one…")
        board = client.create_board()
        board_id = board["id"]
        state["board_id"] = board_id
        save_state(state)

    board = client.get_board(board_id)
    board_url = board.get("viewLink") or f"https://miro.com/app/board/{board_id}/"
    save_url(board_url)

    print(f"Target board: {board_url}")
    print("\nReconciling…")

    try:
        counts = reconcile(client, board_id, widgets, connectors, state,
                           scope_cap=args.cap)
    finally:
        # Always persist whatever progress was made, even on partial failure,
        # so a re-run does not duplicate widgets that were already created.
        save_state(state)
        save_url(board_url)

    print(f"\nDone. created={counts['create']} updated={counts['update']} "
          f"deleted={counts['delete']} "
          f"tag_attach={counts.get('tag_attach', 0)} tag_detach={counts.get('tag_detach', 0)}")
    print(f"API calls: {client.api_calls}  retries: {client.retries}")
    print(f"Board URL: {board_url}")
    print(f"State: {STATE_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
